# Site settings
title: Practical Elegance
subtitle: '"Elegance is not a dispensable luxury." - Edsgar Dijkstra'
author: Jason Lewis
simple_search: http://google.com/search
email: jason@decomplecting.org
description: > # this means to ignore newlines until "baseurl:"
  Software development, ire, and song
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://decomplecting.org" # the base hostname & protocol for your site
twitter_username: canweriotnow
github_username:  canweriotnow

date_format: "%Y-%m-%d"
titlecase: false

subscribe_rss: http://feeds.feedburner.com/PracticalElegance

# Build settings
markdown: kramdown
